### PR TITLE
fix: build issue on macos (closes: #27)

### PR DESCRIPTION
**Pull request by MrCyjaneK**
Workarounded the issue, required for https://github.com/cypherstack/stack_wallet/pull/818

### CODE REVIEW

**Review by sneurlax — APPROVED** [review]

**Comment by sneurlax** [comment]
Closes #27

**Comment by julian-CStack** [comment]
@MrCyjaneK Any opinion on https://github.com/cypherstack/flutter_libsparkmobile/pull/29 ?
I'm unfamiliar with the flags in your fix so I'm not sure which is the better solution.

**Comment by MrCyjaneK** [comment]
Your looks cleaner, mine is boost specific. I am in favor of #29 if it works (can't test now)

**Comment by julian-CStack** [comment]
> Your looks cleaner, mine is boost specific. I am in favor of #29 if it works (can't test now)

Ok, I'll leave both open for now awaiting a review on https://github.com/cypherstack/flutter_libsparkmobile/pull/29 and testing testing by you and possibly @sneurlax as well

**Comment by julian-CStack** [comment]
Applied https://github.com/cypherstack/flutter_libsparkmobile/pull/29

**Pull request closed without merging**
